# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
commands =  ['batman',
'beyonce',
'booyakasha',
'burger',
'cash',
'cat',
'champagne',
'coffee',
'coffee',
'confused',
'dance',
'dead',
'early',
'fight club',
'fu',
'game of thrones',
'grrrr',
'hawt',
'heartbreak',
'hello',
'hi',
'hilarious',
'hugs',
'hump day',
'hungover',
'i’m sick',
'key',
'kim kardashian',
'left shark',
'lol',
'love',
'magic',
'miss you',
'omfg',
'pancakes',
'pasta',
'pizza',
'poo',
'puppy',
'roses',
'sad',
'satan',
'sexy',
'sexy time',
'shit',
'shrug',
'single ladies',
'some bunny loves you',
'sports illustrated',
'success',
'superhero',
'superman',
'team',
'terminator',
'thanks',
'tired',
'toilet',
'wawawewa',
'wonder woman',
'yaaasss',
'you fuel my love',
'you go girl',
'you’re the worst']

commands.each {|command| Command.create(name: command)}
